I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 617, in script
    aya "Aya Kataragi."
Exception: Sayer 'aya' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 617, in script
    aya "Aya Kataragi."
  File "renpy/ast.py", line 681, in execute
    who = eval_who(self.who, self.who_fast)
  File "renpy/ast.py", line 574, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'aya' is not defined.

Windows-10-10.0.19041
Ren'Py 7.4.11.2266
RGUIG GAME 1.0
Mon Jun 27 16:39:40 2022
