I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/scene1.rpy", line 273, in script
    "{i}*Regarde un épisode d'Obi-Wan Kenobi*"
IOError: Couldn't find file 'audio/ost/star_wars_op.mp3'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/scene1.rpy", line 273, in script
    "{i}*Regarde un épisode d'Obi-Wan Kenobi*"
  File "/Applications/Renpy/renpy/ast.py", line 721, in execute
    renpy.exports.say(who, what, *args, **kwargs)
  File "/Applications/Renpy/renpy/exports.py", line 1419, in say
    who(what, *args, **kwargs)
  File "/Applications/Renpy/renpy/character.py", line 1249, in __call__
    self.do_display(who, what, cb_args=self.cb_args, dtt=dtt, **display_args)
  File "/Applications/Renpy/renpy/character.py", line 901, in do_display
    **display_args)
  File "/Applications/Renpy/renpy/character.py", line 647, in display_say
    rv = renpy.ui.interact(mouse='say', type=type, roll_forward=roll_forward)
  File "/Applications/Renpy/renpy/ui.py", line 298, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "/Applications/Renpy/renpy/display/core.py", line 3325, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, pause=pause, pause_start=pause_start, **kwargs)
  File "/Applications/Renpy/renpy/display/core.py", line 4025, in interact_core
    renpy.audio.audio.periodic()
  File "/Applications/Renpy/renpy/audio/audio.py", line 1162, in periodic
    raise_(exc[0], exc[1], exc[2])
  File "/Applications/Renpy/renpy/audio/audio.py", line 1140, in periodic_thread_main
    periodic_pass()
  File "/Applications/Renpy/renpy/audio/audio.py", line 1082, in periodic_pass
    c.periodic()
  File "/Applications/Renpy/renpy/audio/audio.py", line 518, in periodic
    topf = load(filename)
  File "/Applications/Renpy/renpy/audio/audio.py", line 69, in load
    rv = renpy.loader.load(fn)
  File "/Applications/Renpy/renpy/loader.py", line 798, in load
    raise IOError("Couldn't find file '%s'." % name)
IOError: Couldn't find file 'audio/ost/star_wars_op.mp3'.

Darwin-21.1.0-x86_64-i386-64bit
Ren'Py 7.4.11.2266
RGUIG GAME 1.0
Mon Aug 15 18:37:50 2022
